sudo:
  - required

dist:
  - trusty

services:
  - docker

script:
  - docker build -t iganesh/openwrt-snapshot-builder:latest -f Dockerfile .
  - docker images

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push iganesh/openwrt-snapshot-builder:latest
